name: ShopSearcher
version: 2.0.0
author: ktm6060
main: ktm6060.shopsearcher.ShopSearcher
api-version: 1.13
description: For use with Display Shop plugin on The Wooden Spoon server.

commands:
  shop:
    description: Shop command.
  myshop:
    description: Opens my shop menu.
  search:
    description: Test command.
  shopsearcher:
    description: Shopsearcher commands.
  ss:
    description: Shortcut for shopsearcher.
  plot:
    description: Plot command.
  
permissions:
  shopsearcher.staff:
    description: Staff level permission, access to staff commands.
    default: false
  shopsearcher.admin:
    description: Admin level permission, access to all plugin commands.
    default: false